In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp312-cp312-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/pavithramg/Documents/CODE/pythonplaykernel/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/pavithramg/Documents/CODE/pythonplaykernel/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 60.6 MB/s eta 0:00:00
Downloading numpy-2.4.4-cp312-cp312-macosx_14_0_arm64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 68.6 MB/s eta 0:00:00
Installing collected packages: numpy, pandas
Successfully installed numpy-2.4.4 pandas-3.0.2

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data.csv")

In [4]:
print(df)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   22     70

In [10]:
df.head()

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   22     70

In [12]:
df.shape

(3, 3)

In [7]:
df.columns
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Score   3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

             Age      Score
count   3.000000   3.000000
mean   25.666667  81.666667
std     4.041452  10.408330
min    22.000000  70.000000
25%    23.500000  77.500000
50%    25.000000  85.000000
75%    27.500000  87.500000
max    30.000000  90.000000