In [2]:
import pandas as pd

df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.groupby("Sex")["Age"].mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [4]:
df.groupby("Sex")["Age"].max()

Sex
female    63.0
male      80.0
Name: Age, dtype: float64

In [5]:
df.groupby("Sex")["Age"].min()

Sex
female    0.75
male      0.42
Name: Age, dtype: float64

In [6]:
df.groupby("Sex")["Age"].agg(["mean", "max", "min"])

             mean   max   min
Sex
female  27.915709  63.0  0.75
male    30.726645  80.0  0.42

In [7]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [8]:
df["Sex"].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [9]:
df["Age"] = df["Age"].apply(lambda x: x+5)

In [10]:
def categorize(age):
    if age >= 18:
        return "Adult"
    else:
        return "Child"

df["AgeGroup"] = df["Age"].apply(categorize)

In [11]:
df["AgeGroup"].value_counts()

AgeGroup
Adult    645
Child    246
Name: count, dtype: int64

In [12]:
df[(df["Age"] > 20) & (df["Sex"] == "female")]["Name"]

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
8      Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
11                              Bonnell, Miss. Elizabeth
                             ...
879        Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
880         Shelley, Mrs. William (Imanita Parrish Hall)
882                         Dahlberg, Miss. Gerda Ulrika
885                 Rice, Mrs. William (Margaret Norton)
887                         Graham, Miss. Margaret Edith
Name: Name, Length: 218, dtype: str

In [13]:
df.groupby("Sex").agg("max")

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup
Sex,,,,,,,,,,,,
female,889,1,3,"de Messemaeker, Mrs. Guillaume Joseph (Emma)",68.0,8,6,WE/P 5735,512.3292,G6,S,Child
male,891,1,3,"van Melkebeke, Mr. Philemon",85.0,8,5,WE/P 5735,512.3292,T,S,Child

In [14]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,34.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,5.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,25.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,33.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,43.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,85.000000,8.000000,6.000000,512.329200

In [15]:
df.groupby("Sex").count()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup
Sex,,,,,,,,,,,,
female,314,314,314,314,261,314,314,314,314,97,312,314
male,577,577,577,577,453,577,577,577,577,107,577,577

In [16]:
df.groupby("Pclass")["Fare"].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [17]:
df.groupby("Pclass")["Fare"].mean().idxmax()

np.int64(1)

In [18]:
df.groupby("Pclass").mean(numeric_only=True)

        PassengerId  Survived        Age     SibSp     Parch       Fare
Pclass
1        461.597222  0.629630  43.233441  0.416667  0.356481  84.154687
2        445.956522  0.472826  34.877630  0.402174  0.380435  20.662183
3        439.154786  0.242363  30.140620  0.615071  0.393075  13.675550

In [19]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
AgeGroup           str
dtype: object

In [20]:
df.sort_values("Name", ascending=True).tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup
286,287,1,3,"de Mulder, Mr. Theodore",male,35.0,0,0,345774,9.5000,NaN,S,Adult
282,283,0,3,"de Pelsmaeker, Mr. Alfons",male,21.0,0,0,345778,9.5000,NaN,S,Adult
361,362,0,2,"del Carlo, Mr. Sebastiano",male,34.0,1,0,SC/PARIS 2167,27.7208,NaN,C,Adult
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,45.5,0,2,A/5. 851,14.5000,NaN,S,Adult
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S,Child